<p style="text-align:center">
    <a href="https://skills.network/?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDS0321ENSkillsNetwork26802033-2022-01-01" target="_blank">
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/assets/logos/SN_web_lightmode.png" width="200" alt="Skills Network Logo"  />
    </a>
</p>

# **Launch Sites Locations Analysis with Folium**

Estimated time needed: **40** minutes

The launch success rate may depend on many factors such as payload mass, orbit type, and so on. It may also depend on the location and proximities of a launch site, i.e., the initial position of rocket trajectories. Finding an optimal location for building a launch site certainly involves many factors and hopefully we could discover some of the factors by analyzing the existing launch site locations.

In the previous exploratory data analysis labs, you have visualized the SpaceX launch dataset using `matplotlib` and `seaborn` and discovered some preliminary correlations between the launch site and success rates. In this lab, you will be performing more interactive visual analytics using `Folium`.

## Objectives

This lab contains the following tasks:

*   **TASK 1:** Mark all launch sites on a map
*   **TASK 2:** Mark the success/failed launches for each site on the map
*   **TASK 3:** Calculate the distances between a launch site to its proximities

After completed the above tasks, you should be able to find some geographical patterns about launch sites.

Let's first import required Python packages for this lab:

In [2]:
import piplite
await piplite.install(['folium'])
await piplite.install(['pandas'])

In [3]:
import folium
import pandas as pd

In [4]:
# Import folium MarkerCluster plugin
from folium.plugins import MarkerCluster
# Import folium MousePosition plugin
from folium.plugins import MousePosition
# Import folium DivIcon plugin
from folium.features import DivIcon

If you need to refresh your memory about folium, you may download and refer to this previous folium lab:

[Generating Maps with Python](https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/labs/module\_3/DV0101EN-3-5-1-Generating-Maps-in-Python-py-v2.0.ipynb)

In [ ]:
## Task 1: Mark all launch sites on a map

First, let's try to add each site's location on a map using site's latitude and longitude coordinates

The following dataset with the name `spacex_launch_geo.csv` is an augmented dataset with latitude and longitude added for each site.

In [6]:
# Download and read the `spacex_launch_geo.csv`
from js import fetch
import io

URL = 'https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/datasets/spacex_launch_geo.csv'
resp = await fetch(URL)
spacex_csv_file = io.BytesIO((await resp.arrayBuffer()).to_py())
spacex_df=pd.read_csv(spacex_csv_file)

Now, you can take a look at what are the coordinates for each site.

In [7]:
# Select relevant sub-columns: `Launch Site`, `Lat(Latitude)`, `Long(Longitude)`, `class`
spacex_df = spacex_df[['Launch Site', 'Lat', 'Long', 'class']]
launch_sites_df = spacex_df.groupby(['Launch Site'], as_index=False).first()
launch_sites_df = launch_sites_df[['Launch Site', 'Lat', 'Long']]
launch_sites_df

    Launch Site        Lat        Long
0   CCAFS LC-40  28.562302  -80.577356
1  CCAFS SLC-40  28.563197  -80.576820
2    KSC LC-39A  28.573255  -80.646895
3   VAFB SLC-4E  34.632834 -120.610745

Above coordinates are just plain numbers that can not give you any intuitive insights about where are those launch sites. If you are very good at geography, you can interpret those numbers directly in your mind. If not, that's fine too. Let's visualize those locations by pinning them on a map.

We first need to create a folium `Map` object, with an initial center location to be NASA Johnson Space Center at Houston, Texas.

In [8]:
# Start location is NASA Johnson Space Center
nasa_coordinate = [29.559684888503615, -95.0830971930759]
site_map = folium.Map(location=nasa_coordinate, zoom_start=10)

We could use `folium.Circle` to add a highlighted circle area with a text label on a specific coordinate. For example,

In [9]:
# Create a blue circle at NASA Johnson Space Center's coordinate with a popup label showing its name
circle = folium.Circle(nasa_coordinate, radius=1000, color='#d35400', fill=True).add_child(folium.Popup('NASA Johnson Space Center'))
# Create a blue circle at NASA Johnson Space Center's coordinate with a icon showing its name
marker = folium.map.Marker(
    nasa_coordinate,
    # Create an icon as a text label
    icon=DivIcon(
        icon_size=(20,20),
        icon_anchor=(0,0),
        html='<div style="font-size: 12; color:#d35400;"><b>%s</b></div>' % 'NASA JSC',
        )
    )
site_map.add_child(circle)
site_map.add_child(marker)

and you should find a small yellow circle near the city of Houston and you can zoom-in to see a larger circle.

Now, let's add a circle for each launch site in data frame `launch_sites`

*TODO:*  Create and add `folium.Circle` and `folium.Marker` for each launch site on the site map

An example of folium.Circle:

`folium.Circle(coordinate, radius=1000, color='#000000', fill=True).add_child(folium.Popup(...))`

An example of folium.Marker:

`folium.map.Marker(coordinate, icon=DivIcon(icon_size=(20,20),icon_anchor=(0,0), html='<div style="font-size: 12; color:#d35400;"><b>%s</b></div>' % 'label', ))`

In [10]:
# Initial the map
site_map = folium.Map(location=nasa_coordinate, zoom_start=5)
launchsites_lists = []
for index, row in launch_sites_df.iterrows():
    row_list = row.tolist()
    mod_list = row_list[1:]
    launchsites_lists.append(mod_list)
print(launchsites_lists)

[[28.56230197, -80.57735648], [28.56319718, -80.57682003], [28.57325457, -80.64689529], [34.63283416, -120.6107455]]

In [11]:
# Initial the map

# For each launch site, add a Circle object based on its coordinate (Lat, Long) values. In addition, add Launch site name as a popup label
circle = folium.Circle(launchsites_lists[0], radius=1000, color='#d35400', fill = True).add_child(folium.Popup('CCAFS LC-40'))
marker = folium.map.Marker(launchsites_lists[0], icon=DivIcon(icon_size=(20,20),icon_anchor=(0,0), html='<div style="font-size: 12; color:#d35400;"><b>%s</b></div>' % 'CCAFS LC-40', ))
site_map.add_child(circle)
site_map.add_child(marker)
#############################################################################################################################################################################################
circle1 = folium.Circle(launchsites_lists[1], radius=1000, color='#d35400', fill = True).add_child(folium.Popup('CCAFS SLC-40'))
marker1 = folium.map.Marker(launchsites_lists[1], icon=DivIcon(icon_size=(20,20),icon_anchor=(0,0), html='<div style="font-size: 12; color:#d35400;"><b>%s</b></div>' % 'CCAFS SLC-40', ))
site_map.add_child(circle1)
site_map.add_child(marker1)
#############################################################################################################################################################################################
circle2 = folium.Circle(launchsites_lists[2], radius=1000, color='#d35400', fill = True).add_child(folium.Popup('KSC LC-39A'))
marker2 = folium.map.Marker(launchsites_lists[2], icon=DivIcon(icon_size=(20,20),icon_anchor=(0,0), html='<div style="font-size: 12; color:#d35400;"><b>%s</b></div>' % 'KSC LC-39A', ))
site_map.add_child(circle2)
site_map.add_child(marker2)
##############################################################################################################################################################################################
circle3 = folium.Circle(launchsites_lists[3], radius=1000, color='#d35400', fill = True).add_child(folium.Popup('VAFB SLC-4E'))
marker3 = folium.map.Marker(launchsites_lists[3], icon=DivIcon(icon_size=(20,20),icon_anchor=(0,0), html='<div style="font-size: 12; color:#d35400;"><b>%s</b></div>' % 'VAFB SLC-4E', ))
site_map.add_child(circle3)
site_map.add_child(marker3)

The generated map with marked launch sites should look similar to the following:

<center>
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/labs/module_3/images/launch_site_markers.png">
</center>

Now, you can explore the map by zoom-in/out the marked areas
, and try to answer the following questions:

*   Are all launch sites in proximity to the Equator line?
*   Are all launch sites in very close proximity to the coast?

Also please try to explain your findings.

In [ ]:
# Task 2: Mark the success/failed launches for each site on the map

Next, let's try to enhance the map by adding the launch outcomes for each site, and see which sites have high success rates.
Recall that data frame spacex_df has detailed launch records, and the `class` column indicates if this launch was successful or not

In [12]:
spacex_df.tail(10)

     Launch Site        Lat       Long  class
46    KSC LC-39A  28.573255 -80.646895      1
47    KSC LC-39A  28.573255 -80.646895      1
48    KSC LC-39A  28.573255 -80.646895      1
49  CCAFS SLC-40  28.563197 -80.576820      1
50  CCAFS SLC-40  28.563197 -80.576820      1
51  CCAFS SLC-40  28.563197 -80.576820      0
52  CCAFS SLC-40  28.563197 -80.576820      0
53  CCAFS SLC-40  28.563197 -80.576820      0
54  CCAFS SLC-40  28.563197 -80.576820      1
55  CCAFS SLC-40  28.563197 -80.576820      0

Next, let's create markers for all launch records.
If a launch was successful `(class=1)`, then we use a green marker and if a launch was failed, we use a red marker `(class=0)`

Note that a launch only happens in one of the four launch sites, which means many launch records will have the exact same coordinate. Marker clusters can be a good way to simplify a map containing many markers having the same coordinate.

Let's first create a `MarkerCluster` object

In [13]:
import folium
from folium.plugins import MarkerCluster

# Step 1: Create the map object with a unique name
site_map = folium.Map(location=[28.5634, -80.5768], zoom_start=10)  # Example coordinates

# Step 2: Create the MarkerCluster object
marker_cluster = MarkerCluster()

# Step 3: Add the MarkerCluster to the map
marker_cluster.add_to(site_map)

*TODO:* Create a new column in `launch_sites` dataframe called `marker_color` to store the marker colors based on the `class` value

In [14]:

# Apply a function to check the value of `class` column
# If class=1, marker_color value will be green
# If class=0, marker_color value will be red
color_list = []
def marker_color(value):
    marker_color_list = []
    for i in value:
        if i == 1:
            marker_color = 'green'
            marker_color_list.append(marker_color)
        elif i == 0:
            marker_color = 'red'
            marker_color_list.append(marker_color)
        else:
            print('no color available')
    color_list.append(marker_color_list)
    return color_list
marker_color(spacex_df['class'])

spacex_df['marker_color']=color_list[0]
print(spacex_df.head())

   Launch Site        Lat       Long  class marker_color
0  CCAFS LC-40  28.562302 -80.577356      0          red
1  CCAFS LC-40  28.562302 -80.577356      0          red
2  CCAFS LC-40  28.562302 -80.577356      0          red
3  CCAFS LC-40  28.562302 -80.577356      0          red
4  CCAFS LC-40  28.562302 -80.577356      0          red

*TODO:* For each launch result in `spacex_df` data frame, add a `folium.Marker` to `marker_cluster`

In [15]:
import folium
from folium.plugins import MarkerCluster

# Step 1: Create the map object with a unique name
site_map = folium.Map(location=[28.5634, -80.5768], zoom_start=10)  # Example coordinates
# For each launch site, add a Circle object based on its coordinate (Lat, Long) values. In addition, add Launch site name as a popup label
circle = folium.Circle(launchsites_lists[0], radius=1000, color='#d35400', fill = True).add_child(folium.Popup('CCAFS LC-40'))
marker = folium.map.Marker(launchsites_lists[0], icon=DivIcon(icon_size=(20,20),icon_anchor=(0,0), html='<div style="font-size: 12; color:#d35400;"><b>%s</b></div>' % 'CCAFS LC-40', ))
site_map.add_child(circle)
site_map.add_child(marker)
#############################################################################################################################################################################################
circle1 = folium.Circle(launchsites_lists[1], radius=1000, color='#d35400', fill = True).add_child(folium.Popup('CCAFS SLC-40'))
marker1 = folium.map.Marker(launchsites_lists[1], icon=DivIcon(icon_size=(20,20),icon_anchor=(0,0), html='<div style="font-size: 12; color:#d35400;"><b>%s</b></div>' % 'CCAFS SLC-40', ))
site_map.add_child(circle1)
site_map.add_child(marker1)
#############################################################################################################################################################################################
circle2 = folium.Circle(launchsites_lists[2], radius=1000, color='#d35400', fill = True).add_child(folium.Popup('KSC LC-39A'))
marker2 = folium.map.Marker(launchsites_lists[2], icon=DivIcon(icon_size=(20,20),icon_anchor=(0,0), html='<div style="font-size: 12; color:#d35400;"><b>%s</b></div>' % 'KSC LC-39A', ))
site_map.add_child(circle2)
site_map.add_child(marker2)
##############################################################################################################################################################################################
circle3 = folium.Circle(launchsites_lists[3], radius=1000, color='#d35400', fill = True).add_child(folium.Popup('VAFB SLC-4E'))
marker3 = folium.map.Marker(launchsites_lists[3], icon=DivIcon(icon_size=(20,20),icon_anchor=(0,0), html='<div style="font-size: 12; color:#d35400;"><b>%s</b></div>' % 'VAFB SLC-4E', ))
site_map.add_child(circle3)
site_map.add_child(marker3)

# Step 2: Create the MarkerCluster object
marker_cluster = MarkerCluster()

# Step 3: Add the MarkerCluster to the map
marker_cluster.add_to(site_map)

# Optional: Add markers to the MarkerCluster
for index, record in spacex_df.iterrows():
    marker = folium.Marker(
        location=[record['Lat'], record['Long']],  # Assuming latitude and longitude columns in your data frame
        icon=folium.Icon(color='white', icon_color=record['marker_color'])  # Customize the Marker's icon based on the launch outcome
    )
    marker_cluster.add_child(marker)

# Display the map
site_map

Your updated map may look like the following screenshots:

<center>
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/labs/module_3/images/launch_site_marker_cluster.png">
</center>

<center>
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/labs/module_3/images/launch_site_marker_cluster_zoomed.png">
</center>

From the color-labeled markers in marker clusters, you should be able to easily identify which launch sites have relatively high success rates.

In [ ]:
# TASK 3: Calculate the distances between a launch site to its proximities

Next, we need to explore and analyze the proximities of launch sites.

Let's first add a `MousePosition` on the map to get coordinate for a mouse over a point on the map. As such, while you are exploring the map, you can easily find the coordinates of any points of interests (such as railway)

In [16]:
# Add Mouse Position to get the coordinate (Lat, Long) for a mouse over on the map
formatter = "function(num) {return L.Util.formatNum(num, 5);};"
mouse_position = MousePosition(
    position='topright',
    separator=' Long: ',
    empty_string='NaN',
    lng_first=False,
    num_digits=20,
    prefix='Lat:',
    lat_formatter=formatter,
    lng_formatter=formatter,
)

site_map.add_child(mouse_position)
site_map

Now zoom in to a launch site and explore its proximity to see if you can easily find any railway, highway, coastline, etc. Move your mouse to these points and mark down their coordinates (shown on the top-left) in order to the distance to the launch site.

Now zoom in to a launch site and explore its proximity to see if you can easily find any railway, highway, coastline, etc. Move your mouse to these points and mark down their coordinates (shown on the top-left) in order to the distance to the launch site.

In [17]:
from math import sin, cos, sqrt, atan2, radians

def calculate_distance(lat1, lon1, lat2, lon2):
    # approximate radius of earth in km
    R = 6373.0

    lat1 = radians(lat1)
    lon1 = radians(lon1)
    lat2 = radians(lat2)
    lon2 = radians(lon2)

    dlon = lon2 - lon1
    dlat = lat2 - lat1

    a = sin(dlat / 2)**2 + cos(lat1) * cos(lat2) * sin(dlon / 2)**2
    c = 2 * atan2(sqrt(a), sqrt(1 - a))

    distance = R * c
    return distance

*TODO:* Mark down a point on the closest coastline using MousePosition and calculate the distance between the coastline point and the launch site.

In [24]:
# find coordinate of the closet coastline
# e.g.,: Lat: 28.56367  Lon: -80.57163
# distance_coastline = calculate_distance(launch_site_lat, launch_site_lon, coastline_lat, coastline_lon)
# Coordinates of the launch site
launch_site_SLC40_lat = 28.5634
launch_site_SLC40_lon = -80.5768

# Coordinates of the closest coastline point
coastline_SLC_40_lat = 28.56381
coastline_SLC_40_lon = -80.5665
distance_coastline = calculate_distance(launch_site_SLC40_lat, launch_site_SLC40_lon, coastline_SLC_40_lat, coastline_SLC_40_lon)
print(distance_coastline)

1.0072574405022712

In [ ]:
# Create and add a folium.Marker on your selected closest coastline point on the map
# Display the distance between coastline point and launch site using the icon property 
# for example
# distance_marker = folium.Marker(
#    coordinate,
#    icon=DivIcon(
#        icon_size=(20,20),
#        icon_anchor=(0,0),
#        html='<div style="font-size: 12; color:#d35400;"><b>%s</b></div>' % "{:10.2f} KM".format(distance),
#        )
#    )

In [ ]:
from folium.plugins import MousePosition

# Create the map object
site_map = folium.Map(location=[28.5634, -80.5768], zoom_start=10)  # Example coordinates

# Add MousePosition plugin to the map
mouse_position = MousePosition()
mouse_position.add_to(site_map)

# Display the map with MousePosition plugin
site_map

In [19]:
# Create the map object
site_map = folium.Map(location=[launch_site_lat, launch_site_lon], zoom_start=10)
# For each launch site, add a Circle object based on its coordinate (Lat, Long) values. In addition, add Launch site name as a popup label
circle = folium.Circle(launchsites_lists[0], radius=1000, color='#d35400', fill = True).add_child(folium.Popup('CCAFS LC-40'))
marker = folium.map.Marker(launchsites_lists[0], icon=DivIcon(icon_size=(20,20),icon_anchor=(0,0), html='<div style="font-size: 12; color:#d35400;"><b>%s</b></div>' % 'CCAFS LC-40', ))
site_map.add_child(circle)
site_map.add_child(marker)
#############################################################################################################################################################################################
circle1 = folium.Circle(launchsites_lists[1], radius=1000, color='#d35400', fill = True).add_child(folium.Popup('CCAFS SLC-40'))
marker1 = folium.map.Marker(launchsites_lists[1], icon=DivIcon(icon_size=(20,20),icon_anchor=(0,0), html='<div style="font-size: 12; color:#d35400;"><b>%s</b></div>' % 'CCAFS SLC-40', ))
site_map.add_child(circle1)
site_map.add_child(marker1)
#############################################################################################################################################################################################
circle2 = folium.Circle(launchsites_lists[2], radius=1000, color='#d35400', fill = True).add_child(folium.Popup('KSC LC-39A'))
marker2 = folium.map.Marker(launchsites_lists[2], icon=DivIcon(icon_size=(20,20),icon_anchor=(0,0), html='<div style="font-size: 12; color:#d35400;"><b>%s</b></div>' % 'KSC LC-39A', ))
site_map.add_child(circle2)
site_map.add_child(marker2)
##############################################################################################################################################################################################
circle3 = folium.Circle(launchsites_lists[3], radius=1000, color='#d35400', fill = True).add_child(folium.Popup('VAFB SLC-4E'))
marker3 = folium.map.Marker(launchsites_lists[3], icon=DivIcon(icon_size=(20,20),icon_anchor=(0,0), html='<div style="font-size: 12; color:#d35400;"><b>%s</b></div>' % 'VAFB SLC-4E', ))
site_map.add_child(circle3)
site_map.add_child(marker3)

# Step 2: Create the MarkerCluster object
marker_cluster = MarkerCluster()

# Step 3: Add the MarkerCluster to the map
marker_cluster.add_to(site_map)

# Optional: Add markers to the MarkerCluster
for index, record in spacex_df.iterrows():
    marker = folium.Marker(
        location=[record['Lat'], record['Long']],  # Assuming latitude and longitude columns in your data frame
        icon=folium.Icon(color='white', icon_color=record['marker_color'])  # Customize the Marker's icon based on the launch outcome
    )
    marker_cluster.add_child(marker)
# Add a marker for the launch site
folium.Marker(
    location=[launch_site_lat, launch_site_lon],
    icon=folium.Icon(color='blue', icon='info-sign'),
    popup='Launch Site'
).add_to(site_map)

# Add a marker for the coastline point
folium.Marker(
    location=[coastline_lat, coastline_lon],
    icon=folium.Icon(color='green', icon='info-sign'),
    popup='Closest Coastline Point'
).add_to(site_map)

*TODO:* Draw a `PolyLine` between a launch site to the selected coastline point

In [ ]:
# Create a `folium.PolyLine` object using the coastline coordinates and launch site coordinate
# lines=folium.PolyLine(locations=coordinates, weight=1)
folium.PolyLine(
    locations=[[launch_site_lat, launch_site_lon], [coastline_lat, coastline_lon]],
    color='red'
).add_to(site_map)

# Display the map with the PolyLine
site_map

Your updated map with distance line should look like the following screenshot:

<center>
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/labs/module_3/images/launch_site_marker_distance.png">
</center>

*TODO:* Similarly, you can draw a line betwee a launch site to its closest city, railway, highway, etc. You need to use `MousePosition` to find the their coordinates on the map first

A railway map symbol may look like this:

<center>
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/labs/module_3/images/railway.png">
</center>

A highway map symbol may look like this:

<center>
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/labs/module_3/images/highway.png">
</center>

A city map symbol may look like this:

<center>
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/labs/module_3/images/city.png">
</center>

In [27]:
# Create a marker with distance to a closest city, railway, highway, etc.
# Draw a line between the marker to the launch site
# Create the map object
site_map = folium.Map(location=[launch_site_lat, launch_site_lon], zoom_start=10)
# For each launch site, add a Circle object based on its coordinate (Lat, Long) values. In addition, add Launch site name as a popup label
circle = folium.Circle(launchsites_lists[0], radius=1000, color='#d35400', fill = True).add_child(folium.Popup('CCAFS LC-40'))
marker = folium.map.Marker(launchsites_lists[0], icon=DivIcon(icon_size=(20,20),icon_anchor=(0,0), html='<div style="font-size: 12; color:#d35400;"><b>%s</b></div>' % 'CCAFS LC-40', ))
site_map.add_child(circle)
site_map.add_child(marker)
#############################################################################################################################################################################################
circle1 = folium.Circle(launchsites_lists[1], radius=1000, color='#d35400', fill = True).add_child(folium.Popup('CCAFS SLC-40'))
marker1 = folium.map.Marker(launchsites_lists[1], icon=DivIcon(icon_size=(20,20),icon_anchor=(0,0), html='<div style="font-size: 12; color:#d35400;"><b>%s</b></div>' % 'CCAFS SLC-40', ))
site_map.add_child(circle1)
site_map.add_child(marker1)
#############################################################################################################################################################################################
circle2 = folium.Circle(launchsites_lists[2], radius=1000, color='#d35400', fill = True).add_child(folium.Popup('KSC LC-39A'))
marker2 = folium.map.Marker(launchsites_lists[2], icon=DivIcon(icon_size=(20,20),icon_anchor=(0,0), html='<div style="font-size: 12; color:#d35400;"><b>%s</b></div>' % 'KSC LC-39A', ))
site_map.add_child(circle2)
site_map.add_child(marker2)
##############################################################################################################################################################################################
circle3 = folium.Circle(launchsites_lists[3], radius=1000, color='#d35400', fill = True).add_child(folium.Popup('VAFB SLC-4E'))
marker3 = folium.map.Marker(launchsites_lists[3], icon=DivIcon(icon_size=(20,20),icon_anchor=(0,0), html='<div style="font-size: 12; color:#d35400;"><b>%s</b></div>' % 'VAFB SLC-4E', ))
site_map.add_child(circle3)
site_map.add_child(marker3)

# Step 2: Create the MarkerCluster object
marker_cluster = MarkerCluster()

# Step 3: Add the MarkerCluster to the map
marker_cluster.add_to(site_map)

# Optional: Add markers to the MarkerCluster
for index, record in spacex_df.iterrows():
    marker = folium.Marker(
        location=[record['Lat'], record['Long']],  # Assuming latitude and longitude columns in your data frame
        icon=folium.Icon(color='white', icon_color=record['marker_color'])  # Customize the Marker's icon based on the launch outcome
    )
    marker_cluster.add_child(marker)
################################################################################################################################################################################
###### CCAFS SLC-40 distance lines
# Add a marker for the launch site
folium.Marker(
    location=[launch_site_SLC40_lat, launch_site_SLC40_lon],
    icon=folium.Icon(color='blue', icon='info-sign'),
    popup='CCFAS SLC-40 Launch Site'
).add_to(site_map)


# Add a marker for the coastline point
folium.Marker(
    location=[coastline_SLC_40_lat, coastline_SLC_40_lon],
    icon=folium.Icon(color='green', icon='info-sign'),
    popup='Closest Coastline Point to CCFAS SLC-40'
).add_to(site_map)


# Add a marker for railroad 
railroad_SLC40_Lat = 28.57197
railroad_SLC40_Lon = -80.58531
distance_railroad_SLC40 = calculate_distance(launch_site_SLC40_lat, launch_site_SLC40_lon,railroad_SLC40_Lat,railroad_SLC40_Lon)
print(f'the railroad distance from SLC 40 is {distance_railroad_SLC40}')
folium.Marker(
    location=[railroad_SLC40_Lat, railroad_SLC40_Lon],
    icon=folium.Icon(color='blue', icon='info-sign'),
    popup='Closest Railroad Point to CCFAS SLC-40'
).add_to(site_map)

# Add a marker for city
mel_SLC40_Lat = 28.05744
mel_SLC40_Lon = -80.58531
distance_citySLC40 = calculate_distance(launch_site_SLC40_lat, launch_site_SLC40_lon,mel_SLC40_Lat,mel_SLC40_Lon)
print(f'the city distance from SLC 40 is {distance_citySLC40}')
folium.Marker(
    location=[mel_SLC40_Lat, mel_SLC40_Lon],
    icon=folium.Icon(color='blue', icon='info-sign'),
    popup='Closest City Point to CCFAS SLC-40'
).add_to(site_map)


# Add a marker for highway
highway_SLC40_Lat = 28.56326
highway_SLC40_Lon = -80.57077
distance_highway_SLC40 = calculate_distance(launch_site_SLC40_lat, launch_site_SLC40_lon,highway_SLC40_Lat,highway_SLC40_Lon)
print(f'the highway distance from SLC 40 is {distance_highway_SLC40}')
folium.Marker(
    location=[highway_SLC40_Lat, highway_SLC40_Lon],
    icon=folium.Icon(color='blue', icon='info-sign'),
    popup='Closest Highway Point to CCFAS SLC-40'
).add_to(site_map)

# Create a `folium.PolyLine` object using the coastline coordinates and launch site coordinate
# lines=folium.PolyLine(locations=coordinates, weight=1)

# distance line for coastline
folium.PolyLine(
    locations=[[launch_site_SLC40_lat, launch_site_SLC40_lon], [coastline_lat, coastline_lon]],
    color='red'
).add_to(site_map)

# distance line for railroad
folium.PolyLine(
    locations=[[launch_site_SLC40_lat, launch_site_SLC40_lon], [railroad_SLC40_Lat, railroad_SLC40_Lon]],
    color='red'
).add_to(site_map)

# distance line for highway
folium.PolyLine(
    locations=[[launch_site_SLC40_lat, launch_site_SLC40_lon], [highway_SLC40_Lat, highway_SLC40_Lon]],
    color='red'
).add_to(site_map)

# distance line for city
folium.PolyLine(
    locations=[[launch_site_SLC40_lat, launch_site_SLC40_lon], [mel_SLC40_Lat, mel_SLC40_Lon]],
    color='red'
).add_to(site_map)

#################################################################################################################################################
#### CCAFS LC-40 
# Add a marker for the launch site
launch_site_LC40_lat = 28.56231
launch_site_LC40_lon = -80.57736
folium.Marker(
    location=[launch_site_LC40_lat, launch_site_LC40_lon],
    icon=folium.Icon(color='blue', icon='info-sign'),
    popup='CCFAS LC-40 Launch Site'
).add_to(site_map)

# Add a marker for the coastline point
coastline_LC40_lat = 28.56215
coastline_LC40_lon = -80.56745
distance_coastline_LC40 = calculate_distance(launch_site_LC40_lat, launch_site_LC40_lon,coastline_LC40_lat,coastline_LC40_lon)
print(f'the coastline distance from LC 40 is {distance_coastline_LC40}')
folium.Marker(
    location=[coastline_LC40_lat, coastline_LC40_lon],
    icon=folium.Icon(color='green', icon='info-sign'),
    popup='Closest Coastline Point to CCFAS LC-40'
).add_to(site_map)


# Add a marker for railroad 
railroad_LC40_Lat = 28.57297
railroad_LC40_Lon = -80.58522
distance_railroad_LC40 = calculate_distance(launch_site_LC40_lat, launch_site_LC40_lon,railroad_LC40_Lat,railroad_LC40_Lon)
print(f'the railroad distance from LC 40 is {distance_railroad_LC40}')
folium.Marker(
    location=[railroad_LC40_Lat, railroad_LC40_Lon],
    icon=folium.Icon(color='blue', icon='info-sign'),
    popup='Closest Railroad Point to CCFAS LC-40'
).add_to(site_map)

# Add a marker for city
Titu_LC40_Lat = 28.61225
Titu_LC40_Lon = -80.80753
distance_cityLC40 = calculate_distance(launch_site_LC40_lat, launch_site_LC40_lon,Titu_LC40_Lat,Titu_LC40_Lon)
print(f'the city distance from LC 40 is {distance_cityLC40}')
folium.Marker(
    location=[Titu_LC40_Lat, Titu_LC40_Lon],
    icon=folium.Icon(color='blue', icon='info-sign'),
    popup='Closest City Point to CCFAS LC-40'
).add_to(site_map)


# Add a marker for highway
highway_LC40_Lat = 28.56212
highway_LC40_Lon = -80.57061
distance_highway_LC40 = calculate_distance(launch_site_LC40_lat, launch_site_LC40_lon,highway_LC40_Lat,highway_LC40_Lon)
print(f'the highway distance from LC 40 is {distance_highway_LC40}')
folium.Marker(
    location=[highway_LC40_Lat, highway_LC40_Lon],
    icon=folium.Icon(color='blue', icon='info-sign'),
    popup='Closest Highway Point to CCFAS LC-40'
).add_to(site_map)

# Create a `folium.PolyLine` object using the coastline coordinates and launch site coordinate
# lines=folium.PolyLine(locations=coordinates, weight=1)

# distance line for coastline
folium.PolyLine(
    locations=[[launch_site_LC40_lat, launch_site_LC40_lon], [coastline_LC40_lat, coastline_LC40_lon]],
    color='blue'
).add_to(site_map)

# distance line for railroad
folium.PolyLine(
    locations=[[launch_site_LC40_lat, launch_site_LC40_lon], [railroad_LC40_Lat, railroad_LC40_Lon]],
    color='blue'
).add_to(site_map)

# distance line for highway
folium.PolyLine(
    locations=[[launch_site_LC40_lat, launch_site_LC40_lon], [highway_LC40_Lat, highway_LC40_Lon]],
    color='blue'
).add_to(site_map)

# distance line for city
folium.PolyLine(
    locations=[[launch_site_LC40_lat, launch_site_LC40_lon], [Titu_LC40_Lat,Titu_LC40_Lon]],
    color='blue'
).add_to(site_map)

############################################################################################################################################################################################
#### KSC LC-39A 
# Add a marker for the launch site
launch_site_LC39_lat = 28.57327
launch_site_LC39_lon = -80.64691
folium.Marker(
    location=[launch_site_LC39_lat, launch_site_LC39_lon],
    icon=folium.Icon(color='blue', icon='info-sign'),
    popup='KSC LC-39A Launch Site'
).add_to(site_map)

# Add a marker for the coastline point
coastline_LC39_lat = 28.58626
coastline_LC39_lon = -80.56506
distance_coastline_LC39 = calculate_distance(launch_site_LC39_lat, launch_site_LC39_lon,coastline_LC39_lat,coastline_LC39_lon)
print(f'the coastline distance from LC 39A is {distance_coastline_LC39}')
folium.Marker(
    location=[coastline_LC39_lat,coastline_LC39_lon],
    icon=folium.Icon(color='green', icon='info-sign'),
    popup='Closest Coastline Point to KSC LC-39A'
).add_to(site_map)


# Add a marker for railroad 
railroad_LC39_Lat = 28.57297
railroad_LC39_Lon = -80.58522
distance_railroad_LC39 = calculate_distance(launch_site_LC39_lat, launch_site_LC39_lon,railroad_LC39_Lat,railroad_LC39_Lon)
print(f'the railroad distance from LC 39A is {distance_railroad_LC39}')
folium.Marker(
    location=[railroad_LC39_Lat, railroad_LC39_Lon],
    icon=folium.Icon(color='blue', icon='info-sign'),
    popup='Closest Railroad Point to KSC LC-39A'
).add_to(site_map)

# Add a marker for city
Titu_LC39_Lat = 28.61014
Titu_LC39_Lon = -80.8091
distance_cityLC39 = calculate_distance(launch_site_LC39_lat, launch_site_LC39_lon,Titu_LC39_Lat,Titu_LC39_Lon)
print(f'the city distance from LC 39A is {distance_cityLC40}')
folium.Marker(
    location=[Titu_LC39_Lat, Titu_LC39_Lon],
    icon=folium.Icon(color='blue', icon='info-sign'),
    popup='Closest City Point to KSC LC-39A'
).add_to(site_map)

# Add a marker for highway
highway_LC39_Lat = 28.57193
highway_LC39_Lon = -80.65545
distance_highway_LC39 = calculate_distance(launch_site_LC39_lat, launch_site_LC39_lon,highway_LC39_Lat,highway_LC39_Lon)
print(f'the highway distance from LC 39A is {distance_highway_LC39}')
folium.Marker(
    location=[highway_LC39_Lat, highway_LC39_Lon],
    icon=folium.Icon(color='blue', icon='info-sign'),
    popup='Closest Highway Point to KSC LC-39A'
).add_to(site_map)

# Create a `folium.PolyLine` object using the coastline coordinates and launch site coordinate
# lines=folium.PolyLine(locations=coordinates, weight=1)

# distance line for coastline
folium.PolyLine(
    locations=[[launch_site_LC39_lat, launch_site_LC39_lon], [coastline_LC39_lat, coastline_LC39_lon]],
    color='green'
).add_to(site_map)

# distance line for railroad
folium.PolyLine(
    locations=[[launch_site_LC39_lat, launch_site_LC39_lon], [railroad_LC39_Lat, railroad_LC39_Lon]],
    color='green'
).add_to(site_map)

# distance line for highway
folium.PolyLine(
    locations=[[launch_site_LC39_lat, launch_site_LC39_lon], [highway_LC39_Lat, highway_LC39_Lon]],
    color='green'
).add_to(site_map)

# distance line for city
folium.PolyLine(
    locations=[[launch_site_LC39_lat, launch_site_LC39_lon], [Titu_LC40_Lat,Titu_LC39_Lon]],
    color='green'
).add_to(site_map)
##########################################################################################################################################
#### VAFB SLC-4E
# Add a marker for the launch site
launch_site_SLC4E_lat = 34.63285
launch_site_SLC4E_lon = -120.61074
folium.Marker(
    location=[launch_site_SLC4E_lat, launch_site_SLC4E_lon],
    icon=folium.Icon(color='blue', icon='info-sign'),
    popup='VAFB SLC-4E Launch Site'
).add_to(site_map)

# Add a marker for the coastline point
coastline_SLC4E_lat = 34.63603
coastline_SLC4E_lon = -120.64061
distance_coastline_SLC4E = calculate_distance(launch_site_SLC4E_lat, launch_site_SLC4E_lon,coastline_SLC4E_lat,coastline_SLC4E_lon)
print(f'the coastline distance from SLC-4E is {distance_coastline_SLC4E}')
folium.Marker(
    location=[coastline_SLC4E_lat,coastline_SLC4E_lon],
    icon=folium.Icon(color='green', icon='info-sign'),
    popup='Closest Coastline Point to VAFB SLC-4E'
).add_to(site_map)


# Add a marker for railroad 
railroad_SLC4E_Lat = 34.63377
railroad_SLC4E_Lon = -120.6246
distance_railroad_SLC4E = calculate_distance(launch_site_SLC4E_lat, launch_site_SLC4E_lon,railroad_SLC4E_Lat,railroad_SLC4E_Lon)
print(f'the railroad distance from SLC-4E is {distance_railroad_SLC4E}')
folium.Marker(
    location=[railroad_SLC4E_Lat, railroad_SLC4E_Lon],
    icon=folium.Icon(color='blue', icon='info-sign'),
    popup='Closest Railroad Point to KSC LC-39A'
).add_to(site_map)

# Add a marker for city
Lom_SLC4E_Lat = 28.61014
Lom_SLC4E_Lon = -80.8091
distance_citySLC4E = calculate_distance(launch_site_SLC4E_lat, launch_site_SLC4E_lon,Lom_SLC4E_Lat,Lom_SLC4E_Lon)
print(f'the city distance from LC 40 is {distance_citySLC4E}')
folium.Marker(
    location=[Lom_SLC4E_Lat, Lom_SLC4E_Lon],
    icon=folium.Icon(color='blue', icon='info-sign'),
    popup='Closest City Point to KSC LC-39A'
).add_to(site_map)

# Add a marker for highway
highway_SLC4E_Lat = 28.57193
highway_SLC4E_Lon = -80.65545
distance_highway_LC39 = calculate_distance(launch_site_SLC4E_lat, launch_site_SLC4E_lon,highway_SLC4E_Lat,highway_SLC4E_Lon)
print(f'the highway distance from LC 39A is {distance_highway_LC39}')
folium.Marker(
    location=[highway_SLC4E_Lat, highway_SLC4E_Lon],
    icon=folium.Icon(color='blue', icon='info-sign'),
    popup='Closest Highway Point to KSC LC-39A'
).add_to(site_map)

# Create a `folium.PolyLine` object using the coastline coordinates and launch site coordinate
# lines=folium.PolyLine(locations=coordinates, weight=1)

# distance line for coastline
folium.PolyLine(
    locations=[[launch_site_SLC4E_lat, launch_site_SLC4E_lon], [coastline_SLC4E_lat, coastline_SLC4E_lon]],
    color='purple'
).add_to(site_map)

# distance line for railroad
folium.PolyLine(
    locations=[[launch_site_SLC4E_lat, launch_site_SLC4E_lon], [railroad_SLC4E_Lat, railroad_SLC4E_Lon]],
    color='purple'
).add_to(site_map)

# distance line for highway
folium.PolyLine(
    locations=[[launch_site_SLC4E_lat, launch_site_SLC4E_lon], [highway_SLC4E_Lat, highway_SLC4E_Lon]],
    color='purple'
).add_to(site_map)

# distance line for city
folium.PolyLine(
    locations=[[launch_site_SLC4E_lat, launch_site_SLC4E_lon,], [Lom_SLC4E_Lat,Lom_SLC4E_Lon]],
    color='purple'
).add_to(site_map)
# Display the map with the PolyLine
site_map

the railroad distance from SLC 40 is 1.2648184516454972
the city distance from SLC 40 is 56.28401601291319
the highway distance from SLC 40 is 0.589288288651223
the coastline distance from LC 40 is 0.9683009750809081
the railroad distance from LC 40 is 1.4126100217466933
the city distance from LC 40 is 23.15674668296185
the highway distance from LC 40 is 0.6597662615070312
the coastline distance from LC 39A is 8.124351843878658
the railroad distance from LC 39A is 6.026148492135723
the city distance from LC 39A is 23.15674668296185
the highway distance from LC 39A is 0.8474263015259388
the coastline distance from SLC-4E is 2.7564709603004856
the railroad distance from SLC-4E is 1.2725963027292255
the city distance from LC 40 is 3803.974566213858
the highway distance from LC 39A is 3819.5199249443094

In [31]:
# Create a marker with distance to a closest city, railway, highway, etc.
# Draw a line between the marker to the launch site
# Create the map object
site_map = folium.Map(location=[launch_site_lat, launch_site_lon], zoom_start=10)
# For each launch site, add a Circle object based on its coordinate (Lat, Long) values. In addition, add Launch site name as a popup label
circle = folium.Circle(launchsites_lists[0], radius=1000, color='#d35400', fill = True).add_child(folium.Popup('CCAFS LC-40'))
marker = folium.map.Marker(launchsites_lists[0], icon=DivIcon(icon_size=(20,20),icon_anchor=(0,0), html='<div style="font-size: 12; color:#d35400;"><b>%s</b></div>' % 'CCAFS LC-40', ))
site_map.add_child(circle)
site_map.add_child(marker)
#############################################################################################################################################################################################
circle1 = folium.Circle(launchsites_lists[1], radius=1000, color='#d35400', fill = True).add_child(folium.Popup('CCAFS SLC-40'))
marker1 = folium.map.Marker(launchsites_lists[1], icon=DivIcon(icon_size=(20,20),icon_anchor=(0,0), html='<div style="font-size: 12; color:#d35400;"><b>%s</b></div>' % 'CCAFS SLC-40', ))
site_map.add_child(circle1)
site_map.add_child(marker1)
#############################################################################################################################################################################################
circle2 = folium.Circle(launchsites_lists[2], radius=1000, color='#d35400', fill = True).add_child(folium.Popup('KSC LC-39A'))
marker2 = folium.map.Marker(launchsites_lists[2], icon=DivIcon(icon_size=(20,20),icon_anchor=(0,0), html='<div style="font-size: 12; color:#d35400;"><b>%s</b></div>' % 'KSC LC-39A', ))
site_map.add_child(circle2)
site_map.add_child(marker2)
##############################################################################################################################################################################################
circle3 = folium.Circle(launchsites_lists[3], radius=1000, color='#d35400', fill = True).add_child(folium.Popup('VAFB SLC-4E'))
marker3 = folium.map.Marker(launchsites_lists[3], icon=DivIcon(icon_size=(20,20),icon_anchor=(0,0), html='<div style="font-size: 12; color:#d35400;"><b>%s</b></div>' % 'VAFB SLC-4E', ))
site_map.add_child(circle3)
site_map.add_child(marker3)

# Step 2: Create the MarkerCluster object
marker_cluster = MarkerCluster()

# Step 3: Add the MarkerCluster to the map
marker_cluster.add_to(site_map)

# Optional: Add markers to the MarkerCluster
for index, record in spacex_df.iterrows():
    marker = folium.Marker(
        location=[record['Lat'], record['Long']],  # Assuming latitude and longitude columns in your data frame
        icon=folium.Icon(color='white', icon_color=record['marker_color'])  # Customize the Marker's icon based on the launch outcome
    )
    marker_cluster.add_child(marker)
################################################################################################################################################################################
###### CCAFS SLC-40 distance lines
# Add a marker for the launch site
folium.Marker(
    location=[launch_site_SLC40_lat, launch_site_SLC40_lon],
    icon=folium.Icon(color='blue', icon='info-sign'),
    popup='CCFAS SLC-40 Launch Site'
).add_to(site_map)


# Add a marker for the coastline point
folium.Marker(
    location=[coastline_SLC_40_lat, coastline_SLC_40_lon],
    icon=folium.Icon(color='green', icon='info-sign'),
    popup='Closest Coastline Point to CCFAS SLC-40'
).add_to(site_map)


# Add a marker for railroad 
railroad_SLC40_Lat = 28.57197
railroad_SLC40_Lon = -80.58531
distance_railroad_SLC40 = calculate_distance(launch_site_SLC40_lat, launch_site_SLC40_lon,railroad_SLC40_Lat,railroad_SLC40_Lon)
print(f'the railroad distance from SLC 40 is {distance_railroad_SLC40}')
folium.Marker(
    location=[railroad_SLC40_Lat, railroad_SLC40_Lon],
    icon=folium.Icon(color='blue', icon='info-sign'),
    popup='Closest Railroad Point to CCFAS SLC-40'
).add_to(site_map)

# Add a marker for city
Titu_SLC40_Lat = 28.61225
Titu_SLC40_Lon = -80.80753
distance_citySLC40 = calculate_distance(launch_site_SLC40_lat, launch_site_SLC40_lon,Titu_SLC40_Lat,Titu_SLC40_Lon)
print(f'the city distance from SLC 40 is {distance_citySLC40}')
folium.Marker(
    location=[mel_SLC40_Lat, mel_SLC40_Lon],
    icon=folium.Icon(color='blue', icon='info-sign'),
    popup='Closest City Point to CCFAS SLC-40'
).add_to(site_map)


# Add a marker for highway
highway_SLC40_Lat = 28.56326
highway_SLC40_Lon = -80.57077
distance_highway_SLC40 = calculate_distance(launch_site_SLC40_lat, launch_site_SLC40_lon,highway_SLC40_Lat,highway_SLC40_Lon)
print(f'the highway distance from SLC 40 is {distance_highway_SLC40}')
folium.Marker(
    location=[highway_SLC40_Lat, highway_SLC40_Lon],
    icon=folium.Icon(color='blue', icon='info-sign'),
    popup='Closest Highway Point to CCFAS SLC-40'
).add_to(site_map)

# Create a `folium.PolyLine` object using the coastline coordinates and launch site coordinate
# lines=folium.PolyLine(locations=coordinates, weight=1)

# distance line for coastline
folium.PolyLine(
    locations=[[launch_site_SLC40_lat, launch_site_SLC40_lon], [coastline_lat, coastline_lon]],
    color='red'
).add_to(site_map)

# distance line for railroad
folium.PolyLine(
    locations=[[launch_site_SLC40_lat, launch_site_SLC40_lon], [railroad_SLC40_Lat, railroad_SLC40_Lon]],
    color='red'
).add_to(site_map)

# distance line for highway
folium.PolyLine(
    locations=[[launch_site_SLC40_lat, launch_site_SLC40_lon], [highway_SLC40_Lat, highway_SLC40_Lon]],
    color='red'
).add_to(site_map)

# distance line for city
folium.PolyLine(
    locations=[[launch_site_SLC40_lat, launch_site_SLC40_lon], [Titu_SLC40_Lat, Titu_SLC40_Lon]],
    color='red'
).add_to(site_map)

#################################################################################################################################################
#### CCAFS LC-40 
# Add a marker for the launch site
launch_site_LC40_lat = 28.56231
launch_site_LC40_lon = -80.57736
folium.Marker(
    location=[launch_site_LC40_lat, launch_site_LC40_lon],
    icon=folium.Icon(color='blue', icon='info-sign'),
    popup='CCFAS LC-40 Launch Site'
).add_to(site_map)

# Add a marker for the coastline point
coastline_LC40_lat = 28.56215
coastline_LC40_lon = -80.56745
distance_coastline_LC40 = calculate_distance(launch_site_LC40_lat, launch_site_LC40_lon,coastline_LC40_lat,coastline_LC40_lon)
print(f'the coastline distance from LC 40 is {distance_coastline_LC40}')
folium.Marker(
    location=[coastline_LC40_lat, coastline_LC40_lon],
    icon=folium.Icon(color='green', icon='info-sign'),
    popup='Closest Coastline Point to CCFAS LC-40'
).add_to(site_map)


# Add a marker for railroad 
railroad_LC40_Lat = 28.57297
railroad_LC40_Lon = -80.58522
distance_railroad_LC40 = calculate_distance(launch_site_LC40_lat, launch_site_LC40_lon,railroad_LC40_Lat,railroad_LC40_Lon)
print(f'the railroad distance from LC 40 is {distance_railroad_LC40}')
folium.Marker(
    location=[railroad_LC40_Lat, railroad_LC40_Lon],
    icon=folium.Icon(color='blue', icon='info-sign'),
    popup='Closest Railroad Point to CCFAS LC-40'
).add_to(site_map)

# Add a marker for city
Titu_LC40_Lat = 28.61225
Titu_LC40_Lon = -80.80753
distance_cityLC40 = calculate_distance(launch_site_LC40_lat, launch_site_LC40_lon,Titu_LC40_Lat,Titu_LC40_Lon)
print(f'the city distance from LC 40 is {distance_cityLC40}')
folium.Marker(
    location=[Titu_LC40_Lat, Titu_LC40_Lon],
    icon=folium.Icon(color='blue', icon='info-sign'),
    popup='Closest City Point to CCFAS LC-40'
).add_to(site_map)


# Add a marker for highway
highway_LC40_Lat = 28.56212
highway_LC40_Lon = -80.57061
distance_highway_LC40 = calculate_distance(launch_site_LC40_lat, launch_site_LC40_lon,highway_LC40_Lat,highway_LC40_Lon)
print(f'the highway distance from LC 40 is {distance_highway_LC40}')
folium.Marker(
    location=[highway_LC40_Lat, highway_LC40_Lon],
    icon=folium.Icon(color='blue', icon='info-sign'),
    popup='Closest Highway Point to CCFAS LC-40'
).add_to(site_map)

# Create a `folium.PolyLine` object using the coastline coordinates and launch site coordinate
# lines=folium.PolyLine(locations=coordinates, weight=1)

# distance line for coastline
folium.PolyLine(
    locations=[[launch_site_LC40_lat, launch_site_LC40_lon], [coastline_LC40_lat, coastline_LC40_lon]],
    color='blue'
).add_to(site_map)

# distance line for railroad
folium.PolyLine(
    locations=[[launch_site_LC40_lat, launch_site_LC40_lon], [railroad_LC40_Lat, railroad_LC40_Lon]],
    color='blue'
).add_to(site_map)

# distance line for highway
folium.PolyLine(
    locations=[[launch_site_LC40_lat, launch_site_LC40_lon], [highway_LC40_Lat, highway_LC40_Lon]],
    color='blue'
).add_to(site_map)

# distance line for city
folium.PolyLine(
    locations=[[launch_site_LC40_lat, launch_site_LC40_lon], [Titu_LC40_Lat,Titu_LC40_Lon]],
    color='blue'
).add_to(site_map)

############################################################################################################################################################################################
#### KSC LC-39A 
# Add a marker for the launch site
launch_site_LC39_lat = 28.57327
launch_site_LC39_lon = -80.64691
folium.Marker(
    location=[launch_site_LC39_lat, launch_site_LC39_lon],
    icon=folium.Icon(color='blue', icon='info-sign'),
    popup='KSC LC-39A Launch Site'
).add_to(site_map)

# Add a marker for the coastline point
coastline_LC39_lat = 28.58626
coastline_LC39_lon = -80.56506
distance_coastline_LC39 = calculate_distance(launch_site_LC39_lat, launch_site_LC39_lon,coastline_LC39_lat,coastline_LC39_lon)
print(f'the coastline distance from LC 39A is {distance_coastline_LC39}')
folium.Marker(
    location=[coastline_LC39_lat,coastline_LC39_lon],
    icon=folium.Icon(color='green', icon='info-sign'),
    popup='Closest Coastline Point to KSC LC-39A'
).add_to(site_map)


# Add a marker for railroad 
railroad_LC39_Lat = 28.57297
railroad_LC39_Lon = -80.58522
distance_railroad_LC39 = calculate_distance(launch_site_LC39_lat, launch_site_LC39_lon,railroad_LC39_Lat,railroad_LC39_Lon)
print(f'the railroad distance from LC 39A is {distance_railroad_LC39}')
folium.Marker(
    location=[railroad_LC39_Lat, railroad_LC39_Lon],
    icon=folium.Icon(color='blue', icon='info-sign'),
    popup='Closest Railroad Point to KSC LC-39A'
).add_to(site_map)

# Add a marker for city
Titu_LC39_Lat = 28.61014
Titu_LC39_Lon = -80.8091
distance_cityLC39 = calculate_distance(launch_site_LC39_lat, launch_site_LC39_lon,Titu_LC39_Lat,Titu_LC39_Lon)
print(f'the city distance from LC 39A is {distance_cityLC40}')
folium.Marker(
    location=[Titu_LC39_Lat, Titu_LC39_Lon],
    icon=folium.Icon(color='blue', icon='info-sign'),
    popup='Closest City Point to KSC LC-39A'
).add_to(site_map)

# Add a marker for highway
highway_LC39_Lat = 28.57193
highway_LC39_Lon = -80.65545
distance_highway_LC39 = calculate_distance(launch_site_LC39_lat, launch_site_LC39_lon,highway_LC39_Lat,highway_LC39_Lon)
print(f'the highway distance from LC 39A is {distance_highway_LC39}')
folium.Marker(
    location=[highway_LC39_Lat, highway_LC39_Lon],
    icon=folium.Icon(color='blue', icon='info-sign'),
    popup='Closest Highway Point to KSC LC-39A'
).add_to(site_map)

# Create a `folium.PolyLine` object using the coastline coordinates and launch site coordinate
# lines=folium.PolyLine(locations=coordinates, weight=1)

# distance line for coastline
folium.PolyLine(
    locations=[[launch_site_LC39_lat, launch_site_LC39_lon], [coastline_LC39_lat, coastline_LC39_lon]],
    color='green'
).add_to(site_map)

# distance line for railroad
folium.PolyLine(
    locations=[[launch_site_LC39_lat, launch_site_LC39_lon], [railroad_LC39_Lat, railroad_LC39_Lon]],
    color='green'
).add_to(site_map)

# distance line for highway
folium.PolyLine(
    locations=[[launch_site_LC39_lat, launch_site_LC39_lon], [highway_LC39_Lat, highway_LC39_Lon]],
    color='green'
).add_to(site_map)

# distance line for city
folium.PolyLine(
    locations=[[launch_site_LC39_lat, launch_site_LC39_lon], [Titu_LC40_Lat,Titu_LC39_Lon]],
    color='green'
).add_to(site_map)
##########################################################################################################################################
#### VAFB SLC-4E
# Add a marker for the launch site
launch_site_SLC4E_lat = 34.63285
launch_site_SLC4E_lon = -120.61074
folium.Marker(
    location=[launch_site_SLC4E_lat, launch_site_SLC4E_lon],
    icon=folium.Icon(color='blue', icon='info-sign'),
    popup='VAFB SLC-4E Launch Site'
).add_to(site_map)

# Add a marker for the coastline point
coastline_SLC4E_lat = 34.63603
coastline_SLC4E_lon = -120.64061
distance_coastline_SLC4E = calculate_distance(launch_site_SLC4E_lat, launch_site_SLC4E_lon,coastline_SLC4E_lat,coastline_SLC4E_lon)
print(f'the coastline distance from SLC-4E is {distance_coastline_SLC4E}')
folium.Marker(
    location=[coastline_SLC4E_lat,coastline_SLC4E_lon],
    icon=folium.Icon(color='green', icon='info-sign'),
    popup='Closest Coastline Point to VAFB SLC-4E'
).add_to(site_map)


# Add a marker for railroad 
railroad_SLC4E_Lat = 34.63377
railroad_SLC4E_Lon = -120.6246
distance_railroad_SLC4E = calculate_distance(launch_site_SLC4E_lat, launch_site_SLC4E_lon,railroad_SLC4E_Lat,railroad_SLC4E_Lon)
print(f'the railroad distance from SLC-4E is {distance_railroad_SLC4E}')
folium.Marker(
    location=[railroad_SLC4E_Lat, railroad_SLC4E_Lon],
    icon=folium.Icon(color='blue', icon='info-sign'),
    popup='Closest Railroad Point to KSC LC-39A'
).add_to(site_map)

# Add a marker for city
Lom_SLC4E_Lat = 34.63801
Lom_SLC4E_Lon = -120.45753
distance_citySLC4E = calculate_distance(launch_site_SLC4E_lat, launch_site_SLC4E_lon,Lom_SLC4E_Lat,Lom_SLC4E_Lon)
print(f'the city distance from LC 40 is {distance_citySLC4E}')
folium.Marker(
    location=[Lom_SLC4E_Lat, Lom_SLC4E_Lon],
    icon=folium.Icon(color='blue', icon='info-sign'),
    popup='Closest City Point to KSC LC-39A'
).add_to(site_map)

# Add a marker for highway
highway_SLC4E_Lat = 34.65686
highway_SLC4E_Lon = -120.5407
distance_highway_LC39 = calculate_distance(launch_site_SLC4E_lat, launch_site_SLC4E_lon,highway_SLC4E_Lat,highway_SLC4E_Lon)
print(f'the highway distance from LC 39A is {distance_highway_LC39}')
folium.Marker(
    location=[highway_SLC4E_Lat, highway_SLC4E_Lon],
    icon=folium.Icon(color='blue', icon='info-sign'),
    popup='Closest Highway Point to KSC LC-39A'
).add_to(site_map)

# Create a `folium.PolyLine` object using the coastline coordinates and launch site coordinate
# lines=folium.PolyLine(locations=coordinates, weight=1)

# distance line for coastline
folium.PolyLine(
    locations=[[launch_site_SLC4E_lat, launch_site_SLC4E_lon], [coastline_SLC4E_lat, coastline_SLC4E_lon]],
    color='purple'
).add_to(site_map)

# distance line for railroad
folium.PolyLine(
    locations=[[launch_site_SLC4E_lat, launch_site_SLC4E_lon], [railroad_SLC4E_Lat, railroad_SLC4E_Lon]],
    color='purple'
).add_to(site_map)

# distance line for highway
folium.PolyLine(
    locations=[[launch_site_SLC4E_lat, launch_site_SLC4E_lon], [highway_SLC4E_Lat, highway_SLC4E_Lon]],
    color='purple'
).add_to(site_map)

# distance line for city
folium.PolyLine(
    locations=[[launch_site_SLC4E_lat, launch_site_SLC4E_lon,], [Lom_SLC4E_Lat,Lom_SLC4E_Lon]],
    color='purple'
).add_to(site_map)
# Display the map with the PolyLine
site_map

the railroad distance from SLC 40 is 1.2648184516454972
the city distance from SLC 40 is 23.181017338426734
the highway distance from SLC 40 is 0.589288288651223
the coastline distance from LC 40 is 0.9683009750809081
the railroad distance from LC 40 is 1.4126100217466933
the city distance from LC 40 is 23.15674668296185
the highway distance from LC 40 is 0.6597662615070312
the coastline distance from LC 39A is 8.124351843878658
the railroad distance from LC 39A is 6.026148492135723
the city distance from LC 39A is 23.15674668296185
the highway distance from LC 39A is 0.8474263015259388
the coastline distance from SLC-4E is 2.7564709603004856
the railroad distance from SLC-4E is 1.2725963027292255
the city distance from LC 40 is 14.033251007589724
the highway distance from LC 39A is 6.943357929780867

After you plot distance lines to the proximities, you can answer the following questions easily:

*   Are launch sites in close proximity to railways?
*   Are launch sites in close proximity to highways?
*   Are launch sites in close proximity to coastline?
*   Do launch sites keep certain distance away from cities?

Also please try to explain your findings.

# Next Steps:

Now you have discovered many interesting insights related to the launch sites' location using folium, in a very interactive way. Next, you will need to build a dashboard using Ploty Dash on detailed launch records.

## Authors

[Pratiksha Verma](https://www.linkedin.com/in/pratiksha-verma-6487561b1/?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDS0321ENSkillsNetwork865-2022-01-01)

## Change Log

| Date (YYYY-MM-DD) | Version | Changed By      | Change Description      |
| ----------------- | ------- | -------------   | ----------------------- |
| 2022-11-09        | 1.0     | Pratiksha Verma | Converted initial version to Jupyterlite|

### <h3 align="center"> IBM Corporation 2022. All rights reserved. <h3/>